"""
Streamlit UI — Enterprise Document Q&A powered by autonomous AI agents.

Two panels:
  - Sidebar: upload PDF / TXT / CSV / XLSX documents (document ingestion).
  - Main:    ask natural-language questions; answers are generated via the
             RAG agent pipeline (retrieve -> reason -> respond).
"""
from __future__ import annotations

import streamlit as st

from agents.agent_orchestrator import AgentOrchestrator
from core.config import settings
from core.exceptions import AppBaseException
from services.document_service import process_document
from services.vector_store_service import add_documents, collection_document_count
from utils.logger import logger

st.set_page_config(page_title="Enterprise Document Q&A", page_icon="📄", layout="wide")


@st.cache_resource
def get_orchestrator() -> AgentOrchestrator:
    return AgentOrchestrator()


if "chat_history" not in st.session_state:
    st.session_state.chat_history = []  # list of (question, answer, sources)

orchestrator = get_orchestrator()

# ---------------------------------------------------------------- Sidebar --
with st.sidebar:
    st.header("📄 Upload Documents")
    st.caption(f"Allowed: {', '.join(settings.ALLOWED_EXTENSIONS)} · "
               f"Max {settings.MAX_FILE_SIZE_MB} MB per file")

    uploaded_files = st.file_uploader(
        "Upload enterprise documents",
        type=[ext.lstrip(".") for ext in settings.ALLOWED_EXTENSIONS],
        accept_multiple_files=True,
    )

    if uploaded_files and st.button("Process & Index Documents", type="primary"):
        progress = st.progress(0.0, text="Starting ingestion...")
        total_chunks = 0
        errors = []

        for i, uploaded_file in enumerate(uploaded_files):
            try:
                file_bytes = uploaded_file.read()
                chunks = process_document(uploaded_file.name, file_bytes)
                added = add_documents(chunks)
                total_chunks += added
                logger.info(f"Indexed '{uploaded_file.name}' ({added} chunks).")
            except AppBaseException as exc:
                errors.append(f"**{uploaded_file.name}**: {exc.message}")
            except Exception as exc:  # noqa: BLE001
                logger.error(f"Unexpected ingestion error: {exc}")
                errors.append(f"**{uploaded_file.name}**: unexpected error, check logs.")
            progress.progress((i + 1) / len(uploaded_files), text=f"Processed {uploaded_file.name}")

        progress.empty()
        if total_chunks:
            st.success(f"✅ Indexed {total_chunks} chunk(s) from {len(uploaded_files) - len(errors)} file(s).")
        for err in errors:
            st.error(err)

    st.divider()
    st.metric("Chunks in vector store", collection_document_count())

    with st.expander("⚙️ Retrieval settings"):
        st.write(f"Chunk size: `{settings.CHUNK_SIZE}` · Overlap: `{settings.CHUNK_OVERLAP}`")
        st.write(f"Top-K retrieval: `{settings.TOP_K}`")
        st.write(f"LLM: `{settings.GEMINI_LLM_MODEL}`")
        st.write(f"Embedding model: `{settings.GEMINI_EMBEDDING_MODEL}`")

# ------------------------------------------------------------------ Main --
st.title("🤖 Enterprise Document Q&A")
st.caption("Ask natural-language questions about your uploaded documents. "
           "Answers are generated by an autonomous RAG agent pipeline "
           "(retrieve → reason → respond) grounded in your documents.")

if collection_document_count() == 0:
    st.info("👈 Upload and index at least one document from the sidebar to get started.")

for question, answer, sources in st.session_state.chat_history:
    with st.chat_message("user"):
        st.write(question)
    with st.chat_message("assistant"):
        st.write(answer)
        if sources:
            st.caption(f"📚 Sources: {', '.join(sources)}")

question = st.chat_input("Ask a question about your documents...")

if question:
    with st.chat_message("user"):
        st.write(question)

    with st.chat_message("assistant"):
        with st.spinner("Retrieving context and reasoning..."):
            try:
                result = orchestrator.run(question)
            except AppBaseException as exc:
                st.error(f"⚠️ {exc.message}")
                result = None
            except Exception as exc:  # noqa: BLE001
                logger.error(f"Unexpected query error: {exc}")
                st.error("⚠️ Something went wrong processing your question. Please try again.")
                result = None

        if result:
            st.write(result.answer)
            if result.sources:
                st.caption(f"📚 Sources: {', '.join(result.sources)}")
            if not result.grounded and result.sources:
                st.warning("This answer could not be fully verified against the source documents.")

            with st.expander("🔍 Agent trace"):
                for step in result.trace:
                    st.write(f"**{step.step.upper()}** — {step.detail}")

            st.session_state.chat_history.append((question, result.answer, result.sources))
